ignore:
  - cmd/

fixes:
  - "github.com/monitoror/::"

coverage:
  status:
    patch: off
    project:
      default: off
      ui:
        flags: ui
      core:
        target: 90%
        flags: core

flags:
  ui:
    paths:
      - "ui/"
  core:
    paths:
      - "!ui/"
