ignore:
  - cmd/

fixes:
  - "github.com/monitoror/::"

coverage:
  status:
    patch: off
    project:
      default:
        base: pr
        threshold: 20
      front:
        paths: "front/"
      back:
        paths: "!front/"
