ignore:
  - cmd/

fixes:
  - "github.com/monitoror/::"

coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  range: 60...80 # default 70...90. red...green

  status:
    patch: off
    project:
      default:
        base: pr
        threshold: 5%
      front:
        paths: "front/"
      back:
        paths: "!front/"
