ignore:
  - cmd/

fixes:
  - "github.com/monitoror/::"

coverage:
  status:
    patch:
      default:
        enabled: no
    project:
      default: off
      front:
        flags: front
      back:
        target: 70%
        flags: back

flags:
  backe:
    paths:
      - front/
  front:
    paths:
      - !front/
