# Branch filter (build only master and tags) this whitelist is ignored in case of pull request
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

# Alias
alias:
  nodejs: &nodejs
    before_install:
      - nvm install 10.15.3
      - npm install -g yarn@latest

  golangCache: &golangCache "$HOME/gopath/pkg/mod"
  nodejsCache: &nodejsCache "front/node_modules"

# Language definition, used for every jobs
language: go
go: 1.12.x
env:
  global:
    - GO111MODULE="on"

# Job definition
jobs:
  include:
    # Tests - Front
    - stage: Tests
      name: "Front"
      <<: *nodejs
      cache:
        directories:
          - *nodejsCache
      install:
        - cd front
        - yarn install
      script:
        - yarn run test
        - bash <(curl -s https://codecov.io/bash) -cF front

    # Tests - Back
    - name: "Back"
      cache:
        directories:
          - *golangCache
      install:
        - go get gotest.tools/gotestsum
        - make install
      script:
        - make test-coverage
        - bash <(curl -s https://codecov.io/bash) -cF back

    # Build
    - stage: Build
      name: "Front & Back"
      if: type != pull_request
      <<: *nodejs
      cache:
        directories:
          - *golangCache
          - *nodejsCache
      install:
        - go get github.com/GeertJohan/go.rice/rice
        - make install
        - cd front
        - yarn install
      script:
        - yarn run build
        - cd ..
        - make build-all

      # Deploy Github Release
      before_deploy:
        - go get github.com/tcnksm/ghr

      deploy:
        - provider: script
          script: ./scripts/github-release
          skip_cleanup: true
          on:
            tags: true

notifications:
  email: false
